[package]
name = "dt-basefold"
description = "Basefold multilinear PCS for zkdtvm-stark-verifier."
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "basefold"
path = "src/lib.rs"

[dependencies]
p3-field.workspace = true
p3-baby-bear.workspace = true
p3-poseidon2.workspace = true
p3-symmetric.workspace = true
p3-dft.workspace = true
p3-matrix.workspace = true
p3-merkle-tree.workspace = true
p3-commit.workspace = true
p3-fri.workspace = true
p3-challenger.workspace = true
p3-util.workspace = true
p3-maybe-rayon.workspace = true

bincode.workspace = true
itertools.workspace = true
num-traits.workspace = true
rand.workspace = true
rayon.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
rand_core = { version = "0.6", default-features = false }
rand_xoshiro = "0.6"

[features]
default = []
basefold = []
