[package]
name = "zkdtvm-stark-verifier"
description = "Standalone verifier for the zkdtvm STARK proof system."
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "zkdtvm_stark_verifier"
path = "src/lib.rs"

[dependencies]
dt-core-executor = { workspace = true }
dt-core-machine = { workspace = true }
dt-stark = { workspace = true }
dt-primitives = { workspace = true }
dt-prover = { workspace = true }
dt-recursion-core = { workspace = true }
native-recursion = { workspace = true }

p3-field = { workspace = true }

serde = { workspace = true }
bincode = { workspace = true }
tracing = { workspace = true }

[features]
default = []
