use std::borrow::Borrow;

use dt_primitives::{sc_poseidon2_hash, SCField};
use dt_recursion::air::{RecursionPublicValues, NUM_PV_ELMS_TO_HASH};
use dt_recursion::machine::RecursionAir;
use dt_recursion::shape::{CHIP_LOG_HEIGHT_THRESHOLD, NUM_SKIP_ROUNDS};
use dt_stark::sumcheck::config::SCStarkGenericConfig;
use dt_stark::sumcheck::proof::SCMachineProof;
use dt_stark::MachineVerificationError;
use p3_field::AbstractField;

use crate::{CoreSC, DTReduceProof, DTVerifyingKey, HashableKey, InnerSC};

pub const COMPRESS_DEGREE: usize = 3;

/// Byte-level entry point for WASM and other FFI consumers.
///
/// Deserializes a bincode-encoded `DTReduceProof` and a VK commitment,
/// then delegates to [`verify_compressed_with_vk_digest`].
///
/// `vk_bytes` accepts either:
/// - a bincode-encoded `DTVerifyingKey` (legacy/full VK form), or
/// - a bincode-encoded `[u32; DIGEST_SIZE]` VK digest.
pub fn verify_compressed_bytes(proof_bytes: &[u8], vk_bytes: &[u8]) -> Result<(), String> {
    let proof: DTReduceProof<InnerSC> =
        bincode::deserialize(proof_bytes).map_err(|e| format!("proof deserialize: {e}"))?;
    let vk_digest = deserialize_vk_digest(vk_bytes)?;
    verify_compressed_with_vk_digest(&proof, &vk_digest).map_err(|e| format!("{e:?}"))
}

fn deserialize_vk_digest(vk_bytes: &[u8]) -> Result<[SCField; crate::DIGEST_SIZE], String> {
    match bincode::deserialize::<DTVerifyingKey>(vk_bytes) {
        Ok(vk) => Ok(vk.hash_babybear()),
        Err(full_vk_err) => {
            let digest: [u32; crate::DIGEST_SIZE] =
                bincode::deserialize(vk_bytes).map_err(|digest_err| {
                    format!(
                        "vk deserialize: expected bincode DTVerifyingKey or [u32; {}] digest; \
                         full vk error: {full_vk_err}; digest error: {digest_err}",
                        crate::DIGEST_SIZE
                    )
                })?;
            Ok(digest.map(SCField::from_canonical_u32))
        }
    }
}

pub fn verify_compressed(
    proof: &DTReduceProof<InnerSC>,
    vk: &DTVerifyingKey,
) -> Result<(), MachineVerificationError<CoreSC>> {
    verify_compressed_with_vk_digest(proof, &vk.hash_babybear())
}

pub fn verify_compressed_with_vk_digest(
    proof: &DTReduceProof<InnerSC>,
    vk_digest: &[SCField; crate::DIGEST_SIZE],
) -> Result<(), MachineVerificationError<CoreSC>> {
    let DTReduceProof {
        vk: compress_vk,
        proof,
    } = proof;

    let machine_proof = SCMachineProof {
        shard_proofs: vec![proof.clone()],
    };

    // Detect machine type from chip_ordering: skinny chips (root_shrink)
    // contain "Poseidon2Skinny*", wide chips (compress) do not.
    let is_skinny = proof
        .chip_ordering
        .keys()
        .any(|k| k.starts_with("Poseidon2Skinny"));

    if is_skinny {
        // Proof was generated by root_shrink machine (penultimate/root layer).
        let config = InnerSC::root_shrink();
        let machine = RecursionAir::<_, COMPRESS_DEGREE>::sc_shrink_machine(config.clone());
        machine.verify(
            compress_vk,
            &machine_proof,
            &mut config.mlchallenger(),
            NUM_SKIP_ROUNDS,
            CHIP_LOG_HEIGHT_THRESHOLD,
        )?;
    } else {
        // Proof was generated by compress machine (early layers / shallow tree).
        let config = InnerSC::default();
        let machine = RecursionAir::<_, COMPRESS_DEGREE>::sc_compress_machine(config.clone());
        machine.verify(
            compress_vk,
            &machine_proof,
            &mut config.mlchallenger(),
            NUM_SKIP_ROUNDS,
            CHIP_LOG_HEIGHT_THRESHOLD,
        )?;
    }

    let public_values: &RecursionPublicValues<_> = proof.public_values.as_slice().borrow();

    if !is_recursion_public_values_valid(public_values) {
        return Err(MachineVerificationError::InvalidPublicValues(
            "recursion public values are invalid",
        ));
    }

    if public_values.is_complete != SCField::one() {
        return Err(MachineVerificationError::InvalidPublicValues(
            "is_complete is not 1",
        ));
    }

    if public_values.dt_vk_digest != *vk_digest {
        return Err(MachineVerificationError::InvalidPublicValues(
            "dt vk hash mismatch",
        ));
    }

    Ok(())
}

fn is_recursion_public_values_valid(public_values: &RecursionPublicValues<SCField>) -> bool {
    let expected_digest =
        sc_poseidon2_hash(public_values.as_array()[..NUM_PV_ELMS_TO_HASH].to_vec());
    public_values.digest == expected_digest
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::DIGEST_SIZE;
    use std::path::PathBuf;

    fn fixture_dir() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../")
    }

    fn load_fixture_bytes() -> Option<(Vec<u8>, Vec<u8>)> {
        let root = fixture_dir();
        let proof_path = root.join("proof.bin");
        let vk_path = root.join("vk.bin");

        if !proof_path.exists() || !vk_path.exists() {
            eprintln!(
                "Fixture files not found at {}. \
                 Generate them with `gen_verifier_fixtures` on a 32GB+ machine. Skipping test.",
                root.display()
            );
            return None;
        }

        let proof_bytes = std::fs::read(&proof_path)
            .unwrap_or_else(|e| panic!("Failed to read {}: {e}", proof_path.display()));
        let vk_bytes = std::fs::read(&vk_path)
            .unwrap_or_else(|e| panic!("Failed to read {}: {e}", vk_path.display()));

        Some((proof_bytes, vk_bytes))
    }

    #[test]
    fn test_verify_compressed_with_fixtures() {
        let Some((proof_bytes, vk_bytes)) = load_fixture_bytes() else {
            return;
        };

        let result = verify_compressed_bytes(&proof_bytes, &vk_bytes);
        assert!(
            result.is_ok(),
            "Compressed proof verification failed: {:?}",
            result.err()
        );
    }

    #[test]
    fn test_verify_compressed_bytes_with_fixture_vk() {
        let Some((proof_bytes, vk_bytes)) = load_fixture_bytes() else {
            return;
        };

        let result = verify_compressed_bytes(&proof_bytes, &vk_bytes);
        assert!(
            result.is_ok(),
            "Byte API fixture VK verification failed: {:?}",
            result.err()
        );
    }

    #[test]
    fn test_verify_compressed_bytes_with_vk_digest() {
        let Some((proof_bytes, vk_bytes)) = load_fixture_bytes() else {
            return;
        };

        let digest_bytes = if vk_bytes.len() == DIGEST_SIZE * std::mem::size_of::<u32>() {
            vk_bytes
        } else {
            let vk: DTVerifyingKey = bincode::deserialize(&vk_bytes).unwrap();
            bincode::serialize(&vk.hash_u32()).unwrap()
        };

        assert_eq!(digest_bytes.len(), DIGEST_SIZE * std::mem::size_of::<u32>());

        let result = verify_compressed_bytes(&proof_bytes, &digest_bytes);
        assert!(
            result.is_ok(),
            "Byte API digest verification failed: {:?}",
            result.err()
        );
    }

    #[test]
    fn test_proof_deserialization() {
        let root = fixture_dir();
        let proof_path = root.join("proof.bin");
        if !proof_path.exists() {
            eprintln!("proof.bin not found, skipping deserialization test.");
            return;
        }

        let proof_bytes = std::fs::read(&proof_path).unwrap();
        let proof: Result<DTReduceProof<InnerSC>, _> = bincode::deserialize(&proof_bytes);
        assert!(
            proof.is_ok(),
            "Failed to deserialize proof.bin: {:?}",
            proof.err()
        );

        let proof = proof.unwrap();
        assert!(
            !proof.proof.public_values.is_empty(),
            "Proof should have non-empty public values"
        );
    }

    #[test]
    fn test_vk_digest_deserialization() {
        let root = fixture_dir();
        let vk_path = root.join("vk.bin");
        if !vk_path.exists() {
            eprintln!("vk.bin not found, skipping VK digest deserialization test.");
            return;
        }

        let vk_bytes = std::fs::read(&vk_path).unwrap();
        let hash = deserialize_vk_digest(&vk_bytes).expect("failed to deserialize vk digest");
        assert_eq!(
            hash.len(),
            DIGEST_SIZE,
            "VK hash should have {DIGEST_SIZE} elements"
        );
        let hash_again = deserialize_vk_digest(&vk_bytes).expect("failed to deserialize vk digest");
        assert_eq!(hash, hash_again, "VK hashing should be deterministic");
    }

    #[test]
    fn test_message_deserialization() {
        let root = fixture_dir();
        let msg_path = root.join("message.bin");
        if !msg_path.exists() {
            eprintln!("message.bin not found, skipping message deserialization test.");
            return;
        }

        let msg_bytes = std::fs::read(&msg_path).unwrap();
        let message: Result<String, _> = bincode::deserialize(&msg_bytes);
        assert!(
            message.is_ok(),
            "Failed to deserialize message.bin: {:?}",
            message.err()
        );

        let message = message.unwrap();
        assert!(!message.is_empty(), "Message should not be empty");
    }

    #[test]
    fn test_verify_with_wrong_vk_fails() {
        let Some((proof_bytes, mut vk_bytes)) = load_fixture_bytes() else {
            return;
        };

        if let Some(byte) = vk_bytes.first_mut() {
            *byte ^= 0x01;
        }

        let result = verify_compressed_bytes(&proof_bytes, &vk_bytes);
        assert!(
            result.is_err(),
            "Verification should fail with a tampered VK"
        );
    }
}
